version: "3.9"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - pokemon_networks
  app:
    build:
      context: .
    container_name: pokemon-stadium
    command: npm run start
    ports:
      - ${PORT}:3000
    depends_on:
      - db
    networks:
      - pokemon_networks
    links:
      - "db"
networks:
  pokemon_networks:
    driver: bridge
