version: "3.9"

services:
  app:
    build:
      context: .
    container_name: pokemon-stadium
    command: npm run start
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - "db"
    networks:
      - pokemon_networks
    links:
      - "db"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - pokemon_networks
networks:
  pokemon_networks:
    driver: bridge
